from building import *

cwd = GetCurrentDir()
src = Split('''
main.c
''')

path = []

if GetDepend(['_WATCHDOG_APP_', 'RT_USING_WDT']):
    path += [cwd]
    src += ['uc_watchdog_app.c']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = path)

Return('group')
