from building import *

cwd = GetCurrentDir()
src = Split('''
main.c
time_service_demo.c
''')

path = []

if GetDepend(['_WATCHDOG_APP_', 'RT_USING_WDT']):
    path += [cwd]
    src += ['uc_watchdog_app.c']

# if GetDepend(['WIOTA_APP_DEMO']):
#     src += ['wolfmqtt_example2.c']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = path)

Return('group')
