#ifndef _MANAGER_LOGIC_CMD_H_
#define _MANAGER_LOGIC_CMD_H_

enum app_ps_cmd_type
{
    //dev property
    APP_CMD_IOTE_PROPERTY_REPORT = 0,
    APP_CMD_AP_PROPERTY_REPORT = 1,

    //state report
    APP_CMD_AP_STATE_REPORT = 10,
    APP_CMD_IOTE_STATE_REPORT = 11, // report dev state

    //pair
    APP_CMD_IOTE_PAIR_REQUEST = 30,
    APP_CMD_NET_PAIR_RESPONSE = 31,
    APP_CMD_IOTE_PAIR_REQUEST_CANCEL = 32,
    APP_CMD_NET_PAIR_CANCEL = 33,
    APP_CMD_NET_CTRL_IOTE_PAIR_IOTE = 34,

    //ctrl
    APP_CMD_NET_CTRL_IOTE = 40,

    //ota
    APP_CMD_UPDATE_VERSION_REQUEST = 50,
    APP_CMD_UPDATE_VERSION_SPONSE = 51,
    APP_CMD_GET_SPECIFIC_DATA_REQUEST = 52,
    APP_CMD_GET_SPECIFIC_DATA_SPONSE = 53,
    APP_CMD_STOP_UPDATE_REQUEST = 54,
    APP_CMD_STOP_UPDATE_SPONSE = 55,
    APP_CMD_GET_UPDATE_STATE_REQUEST = 56,

    //muticast
    APP_CMD_IOTE_MUTICAST_REQUEST = 100,
    APP_CMD_NET_MUTICAST_ASSIGNMENT = 101,

    //config
    APP_CMD_IOTE_REQUEST_NEW_CONFIG = 120,
    APP_CMD_NET_DELIVER_IOTE_CONFIG = 121,
    WIOTA_AP_REQUEST_RESERVE_ADDR = 122,
    MANAGER_LOGIC_RESPONSE_RESERVE_ADDR = 123,

    APP_CMD_AP_REQUEST_IOTE_REPLACE_ADDR = 130,
    APP_CMD_IOTE_RESPONSE_REPLACE_ADDR = 131,

    MANAGER_LOGIC_WIOTA_START = 0xF0000000,
    MANAGER_LOGIC_SEND_RESULT,
    MANAGER_LOGIC_RECV_WIOTA_DATA,        /*recv data from iote*/
    MANAGER_LOGIC_SWITCH_CONTROL_REQUEST, /* server cmd to iote */
    MANAGER_LOGIC_START_REPLACE_ADDR,
    MANAGER_LOGIC_FROM_NETWORK_MESSAGE,

    MANAGER_LOGIC_TO_HTTP_MESSAGE,
    MANAGER_LOGIC_FROM_HTTP_MESSAGE,

    MANAGER_OPERATION_MSG,
    MANAGER_OPERATION_MSG_RESULT,
    MANAGER_OPERATION_RADIO,
    MANAGER_OPERATION_MULTICAST,
    MANAGER_OPERATION_OTA_RADIO,
    MANAGER_OPERATION_OTA_RADIO_RESULT,
    MANAGER_OPERATION_EXIT,

    MANAGER_LOGIC_MQTT_REQUEST,
    MANAGER_LOGIC_MQTT_RESPONSE,
    MANAGER_LOGIC_MQTT_EXE_RESPONSE,

    MANAGER_OTA_DOWNLOAD_REQUEST
};

#endif
