from building import *

cwd = GetCurrentDir()
src = []
path = []

if GetDepend(['WIOTA_APP_DEMO']):
    path += [cwd]
    src += Glob("*.c")

group = DefineGroup('net_passthrough', src, depend = [''], CPPPATH = path)

Return('group')
