#ifndef MANAGER_ADDRESS_H_
#define MANAGER_ADDRESS_H_

#define AP_DEMO_VERSION "v1.0"

#define ADDRESS_DEFAULT_NULL 0
#define SERVER_DEFAULT_ADDRESS 0xFFFFFFF1
#define AP_DEFAULT_ADDRESS 0xD0000000
#define AP_DEFAULT_RADIO_ADDRESS 0xDFFFFFFF
#define AP_MULTICAST_ADDRESS 0xE0000000

#endif
