Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()

path = [cwd + '/inc']

src = Split('''
src/gpio.c
src/spim.c
src/uc_addc.c
src/uc_boot_strap.c
src/uc_exceptions.c
src/uc_i2c.c
src/uc_int.c
src/uc_pwm.c
src/uc_rtc.c
src/uc_spi_flash.c
src/uc_spi.c
src/uc_string.c
src/uc_timer.c
src/uc_uart.c
src/uc_uartx.c
src/uc_utils.c
src/uc_watchdog.c
''')

group = DefineGroup('UC8088_HAL_Drivers', src, depend = [''], CPPPATH = path)

Return('group')
