from building import *

cwd = GetCurrentDir()

src = []
path = []

if GetDepend(['RT_USING_AT', 'AT_USING_SERVER']):
    src += ['at/at_wiota.c', 'at/at_boot.c']

    if GetDepend(['UC8088_FACTORY_TEST']):
        src += ['at/at_factory.c']

if GetDepend(['WIOTA_API_TEST']):
    path += [cwd + '/app/test']
    src += Glob('app/test/*.c')

path += [cwd + '/app/include']
lib = ['libwin_wiota_ap']
libpath = [cwd + '/lib']

group = DefineGroup('PS', src, depend = [''], CPPPATH = path, LIBS = lib, LIBPATH = libpath)

Return('group')
