from building import *

cwd = GetCurrentDir()

src = []
path = []

if GetDepend(['RT_USING_AT', 'AT_USING_SERVER']):
    src += ['at/at_wiota.c', 'at/at_boot.c']

    if GetDepend(['UC8088_FACTORY_TEST']):
        src += ['at/at_factory.c']

if GetDepend(['WIOTA_API_TEST']):
    path += [cwd + '/app/test']
    src += Glob('app/test/*.c')

if GetDepend(['WIOTA_AP_SEND_DATA_DEMO']):
    src += ['test/test_wiota_send_data.c']
    path += [cwd + '/test']

src += [cwd + '/gnss/gnss_driver.c']
path += [cwd + '/app/include']
path += [cwd + '/gnss']

lib = ['libwin_wiota_ap']
lib += ['libNavProcWin']

libpath = [cwd + '/lib']
libpath +=[cwd + '/gnss']

group = DefineGroup('PS', src, depend = [''], CPPPATH = path, LIBS = lib, LIBPATH = libpath)

Return('group')
